apiVerson: apps/v1
kind: Deployment
metadata:
  name: quiz-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quiz-service
  template:
    metadata:
      labels:
        app: quiz-service
    spec:
      containers:
        - name: quiz-service
          image: martin590/com-project1:quiz-service
          ports:
            - containerPort: 5001
          envFrom:
            - configMapRef:
                name: quiz-service-config
            - secretRef:
                name: quiz-service-secrets
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"