apiVerson: apps/v1
kind: Deployment
metadata:
  name: result-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: result-service
  template:
    metadata:
      labels:
        app: result-service
    spec:
      containers:
        - name: result-service
          image: martin590/com-project1:result-service
          ports:
            - containerPort: 5002
          envFrom:
            - configMapRef:
                name: result-service-config
            - secretRef:
                name: result-service-secrets
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: result-service
# spec:
#   selector:
#     app: result-service
#   ports:
#     - protocol: TCP
#       port: 5002
#       targetPort: 5002
#   type: ClusterIP